# Generated by Django 3.1.5 on 2021-01-14 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reset_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField(default=0)),
                ('e_email', models.CharField(max_length=100)),
                ('e_firstname', models.CharField(max_length=100)),
                ('e_lastname', models.CharField(max_length=100)),
                ('e_password', models.CharField(max_length=100)),
                ('e_address', models.CharField(max_length=100)),
                ('e_dob', models.DateField()),
                ('e_company', models.CharField(max_length=100)),
                ('e_mobile', models.IntegerField(default=0)),
                ('e_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_email', models.CharField(max_length=100)),
                ('m_lastname', models.CharField(max_length=100)),
                ('m_password', models.CharField(max_length=100)),
                ('m_address', models.CharField(max_length=100)),
                ('m_dob', models.DateField()),
                ('m_company', models.CharField(max_length=100)),
                ('m_firstname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
