# Generated by Django 3.1.5 on 2021-01-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='m_email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
